Fix Hot reloading using new Fast Refresh method
rio-cloud/create-react-app pull request #35
Opened 2021-02-10 15:51 UTC by fknrio

by using the development build for React/React-DOM from CDN

2021-02-10 16:59 UTC, rkipsch requested changes

2021-02-10 16:59 UTC, rkipsch commented on packages/rio-template-typescript/template/config-overrides.js
> +                externals: webpackMode === 'production' ? externals : externals.map(it => ({...it, entry: it.entryDev || it.entry})),
Please avoid "it" as the variable name and use more expressive naming to follow clean code guidelines. Thx :-)

2021-02-10 19:20 UTC, fknrio commented on packages/rio-template-typescript/template/config-overrides.js
> +                externals: webpackMode === 'production' ? externals : externals.map(it => ({...it, entry: it.entryDev || it.entry})),
Is it fine like this?

2021-02-19 09:27 UTC, rkipsch approved these changes

2021-02-19 09:28 UTC, merged